services:
  db:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/warrior.sql:/docker-entrypoint-initdb.d/warrior.sql
      - db_data:/var/lib/mysql
    networks:
      - loadbalancing

  app_1:
    build: ./app
    environment:
      - PORT=5000
    depends_on:
      - db
    deploy:
      replicas: 2
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - app_1

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - loadbalancing

networks:
  loadbalancing:

volumes:
  db_data:
