version: "2"
services:
  db:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/warrior.sql:/docker-entrypoint-initdb.d/warrior.sql
      - db_data:/var/lib/mysql
    networks:
      - app-to-db

  app_1:
    build: ./app
    environment:
      - PORT=5000
    depends_on:
      - db
    networks:
      - app-to-db

  app_2:
    build: ./app
    networks:
      - app-to-db
    environment:
      - PORT=5000
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - app-to-db
    depends_on:
      - app_1
      - app_2

networks:
  app-to-db:

volumes:
  db_data:
