version: "2"
services:
  db:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/warrior.sql:/docker-entrypoint-initdb.d/warrior.sql
      - db_data:/var/lib/mysql

  app_1:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  app_2:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:
  db_data: