# This workflow will install Python dependencies, run tests and lint with a single version of Python 
# It builds and deploys the Docker container using Docker compose with build instructions and deployment setting configuration.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Warrior API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    - name: Build and Deploy Docker container
      run: |
        docker-compose up -d --build
    - name: Test with pytest
      run: |
        app_1-1_id=$(docker ps --filter "name=app_1-1" | awk 'NR>1 {print $1}')
        app_1-2_id=$(docker ps --filter "name=app_1-2" | awk 'NR>1 {print $1}')
        docker exec $app_1-1_id pytest
        docker exec $app_1-2_id pytest

        
